SampleGameBConfig:
  type: object
  properties:
    interface_type:
      type: str
      required: true
      default: "cli"
      enum: ["cli", "webui"]
    interface_config:
      type: InterfaceConfig
      required: true
    llm_config:
      type: LLMConfig
      required: true
    transformation_config:
      type: TransformationConfig
      required: true
    scenario_name:
      type: string
      required: true
      default: "Sample Game B: Default Scenario"
    difficulty:
      type: string
      required: true
      default: easy
      enum: [easy, normal, hard]