GenerationConfig:
  type: object
  properties:
    max_tokens:
      type: integer
      required: false
      default: 600
      minimum: 100
      maximum: 1000
    temperature:
      type: float
      required: false
      default: 1
    top_p:
      type: float
      required: false
      default: 1
    # TEMPORARY, refactor or move
    openai_n:
      type: float
      required: false
      default: 1
    openai_stop:
      type: list
      required: false
      default: []
    openai_presence_penalty:
      type: float
      required: false
      default: 0
    openai_frequency_penalty:
      type: float
      required: false
      default: 0
