GenerationConfig:
  type: object
  properties:
    max_tokens:
      type: integer
      required: false
      default: 500
      minimum: 100
      maximum: 1000
    character:
      type: str
      required: false
      default: null
    temperature:
      type: float
      required: false
      default: 1
    top_p:
      type: float
      required: false
      default: 1
    n:
      type: float
      required: false
      default: 1
    stop:
      type: list
      required: false
      default: []
    presence_penalty:
      type: float
      required: false
      default: 0
    frequency_penalty:
      type: float
      required: false
      default: 0
