ChatState:
  type: object
  properties:
    chat_history:
      type: list
      required: true
      default: []
    llm_io_history:
      type: list
      required: true
      default: []
    hidden_data:
      type: object
      required: true
      default: {}
    situational_flags:
      type: object
      required: true
      default: {}
