Config:
  type: object
  properties:
    interface_type:
      type: str
      required: true
      default: "cli"
      enum: ["api", "cli", "webui"]
    interface_config:
      type: InterfaceConfig
      required: true
    llm_config:
      type: LLMConfig
      required: true
    transformation_config:
      type: TransformationConfig
      required: true
# Additional parameters are only in subclasses
