State:
  type: object
  properties:
    chat_history:
      type: list
      required: true
      default: []
    llm_io_history:
      type: list
      required: true
      default: []
# Additional parameters are only in subclasses
