ParsingConfig:
  type: object
  properties:
    user_input_parsings:
      type: list
      required: true
      default: []
    llm_output_parsings:
      type: list
      required: true
      default: []
      
