TransformationConfig:
  type: object
  properties:
    user_input_transformations:
      type: list
      required: true
      default: 
        - name: "cleanup_whitespace"
    llm_output_transformations:
      type: list
      required: true
      default: 
        - name: "cleanup_whitespace"


      # - name: prepend_prefix
      #   args:
      #     prefix: "PREFIX - "
      # - name: append_suffix
      #   args:
      #     suffix: " - SUFFIX"
          
