HFTGIBackendConfig:
  type: object
  properties:
    name_of_model:
      type: str
      required: true
      default: "llama2"
    backend_model_settings:
      type: dict
      required: true
      default: 
        model: "llama2"
        context_limit: 2000
