OobaboogaBackendConfig:
  type: object
  properties:
    name_of_model:
      type: str
      required: true
      default: "llama2-chat"
    model_settings:
      type: dict
      required: true
      default: 
        model: "llama2-chat"
        context_limit: 2000
