SampleGameAConfig:
  type: object
  properties:
    llm_config:
      type: LLMConfig
      required: true
    transformation_config:
      type: TransformationConfig
      required: true
    parsing_config:
      type: ParsingConfig
      required: true
    scenario_name:
      type: string
      required: true
      default: "Sample Game A: Default Scenario"
    difficulty:
      type: string
      required: true
      default: normal
      enum: [easy, normal, hard]